Include all Arch headers on Windows now that ICU is removed
The Windows exclusion guard in Arch/Arch.h was a workaround for ICU
module conflicts (headers including <string> triggered ICU loading).
Now that ICU is removed, all Arch headers can be included on Windows.

This fixes: error: use of undeclared identifier 'ArchGetPrettierFunctionName'